export const countryName: string = "Argentina";

export const statesData = [
  {
    name: "Buenos Aires",
    zones: [
      "Adolfo Alsina",
      "Adolfo González Chaves",
      "Alberti",
      "Almirante Brown",
      "Arrecifes",
      "Avellaneda",
      "Ayacucho",
      "Azul",
      "Bahía Blanca",
      "Balcarce",
      "Baradero",
      "Benito Juárez",
      "Berazategui",
      "Berisso",
      "Bolívar",
      "Bragado",
      "Brandsen",
      "Campana",
      "Capitán Sarmiento",
      "Carlos Casares",
      "Carlos Tejedor",
      "Carmen de Areco",
      "Castelli",
      "Colón",
      "Coronel Dorrego",
      "Coronel Pringles",
      "Coronel Rosales",
      "Coronel Suárez",
      "Chacabuco",
      "Chascomús",
      "Chivilcoy",
      "Daireaux",
      "Dolores",
      "Ensenada",
      "Escobar",
      "Esteban Echeverría",
      "Exaltación de la Cruz",
      "Ezeiza",
      "Florencio Varela",
      "Florentino Ameghino",
      "General Alvarado",
      "General Alvear",
      "General Arenales",
      "General Belgrano",
      "General Guido",
      "General La Madrid",
      "General Las Heras",
      "General Lavalle",
      "General Madariaga",
      "General Paz",
      "General Pinto",
      "General Pueyrredón",
      "General Rodríguez",
      "General San Martín",
      "General Viamonte",
      "General Villegas",
      "Guaminí",
      "Hipólito Yrigoyen",
      "Hurlingham",
      "Ituzaingó",
      "José C. Paz",
      "Junín",
      "La Costa",
      "La Matanza",
      "La Plata",
      "Lanús",
      "Laprida",
      "Las Flores",
      "Leandro N. Alem",
      "Lezama",
      "Lincoln",
      "Lobería",
      "Lobos",
      "Lomas de Zamora",
      "Lujan",
      "Magdalena",
      "Maipú",
      "Malvinas Argentinas",
      "Mar Chiquita",
      "Marcos Paz",
      "Mercedes",
      "Merlo",
      "Monte Hermoso",
      "Moreno",
      "Morón",
      "Navarro",
      "Necochea",
      "Nueve de Julio",
      "Olavarría",
      "Patagones",
      "Pehuajó",
      "Pellegrini",
      "Pergamino",
      "Pila",
      "Pilar",
      "Pinamar",
      "Presidente Perón",
      "Punta Indio",
      "Quilmes",
      "Ramallo",
      "Rauch",
      "Rivadavia",
      "Rojas",
      "Roque Pérez",
      "Saavedra",
      "Saladillo",
      "Salliquelo",
      "Salto",
      "San Andrés de Giles",
      "San Antonio de Areco",
      "San Cayetano",
      "San Fernando",
      "San Isidro",
      "San Miguel",
      "San Miguel del Monte",
      "San Nicolás",
      "San Pedro",
      "San Vicente",
      "Suipacha",
      "Tandil",
      "Tapalqué",
      "Tigre",
      "Tordillo",
      "Tornquist",
      "Trenque Lauquen",
      "Tres Arroyos",
      "Tres de Febrero",
      "Tres Lomas",
      "Veinticinco de Mayo",
      "Vicente López",
      "Villa Gesell",
      "Villarino",
      "Zárate",
    ],
  },
  {
    name: "Catamarca",
    zones: [
      "Aconquija",
      "Ancasti",
      "Andalgalá",
      "Antofagasta de la Sierra",
      "Belén",
      "Capayán",
      "Corral Quemado",
      "El Alto",
      "El Rodeo",
      "Fiambalá",
      "Fray Mamerto Esquiú",
      "Hualfín",
      "Huillapima",
      "Icaño",
      "La Puerta",
      "Las Juntas",
      "Londres",
      "Los Altos",
      "Los Varela",
      "Mutquín",
      "Paclín",
      "Poman",
      "Pozo de Piedra",
      "Puerta de Corral Quemado",
      "Puerta de San José",
      "Recreo",
      "San Fernando",
      "San Fernando del Valle de Catamarca",
      "San José",
      "Santa María",
      "Santa Rosa",
      "Saujil",
      "Tapso",
      "Tinogasta",
      "Valle Viejo",
      "Villa Vil",
    ],
  },
  {
    name: "Chaco",
    zones: [
      "Aviá Teraí",
      "Barranqueras",
      "Basail",
      "Campo Largo",
      "Capitán Solari",
      "Charadai",
      "Charata",
      "Chorotis",
      "Ciervo Petiso",
      "Colonia Aborigen",
      "Colonia Benítez",
      "Colonia Elisa",
      "Colonia Popular",
      "Colonias Unidas",
      "Concepción del Bermejo",
      "Coronel Du Graty",
      "Corzuela",
      "Cote Lai",
      "El Espinillo",
      "El Sauzalito",
      "Enrique Urién",
      "Fontana",
      "Fuerte Esperanza",
      "Gancedo",
      "General Capdevila",
      "General José de San Martín",
      "General Pinedo",
      "General Vedia",
      "Hermoso Campo",
      "Isla del Cerrito",
      "Juan José Castelli",
      "La Clotilde",
      "La Eduvigis",
      "La Escondida",
      "La Leonesa",
      "La Tigra",
      "La Verde",
      "Laguna Blanca",
      "Laguna Limpia",
      "Lapachito",
      "Las Breñas",
      "Las Garcitas",
      "Las Palmas",
      "Los Frentones",
      "Machagai",
      "Makallé",
      "Margarita Belén",
      "Miraflores",
      "Misión Nueva Pompeya",
      "Napenay",
      "Pampa Almirón",
      "Pampa del Indio",
      "Pampa del Infierno",
      "Presidencia de la Plaza",
      "Presidencia Roca",
      "Presidencia Roque Sáenz Peña",
      "Puerto Bermejo",
      "Puerto Eva Perón",
      "Puerto Tirol",
      "Puerto Vilelas",
      "Quitilipi",
      "Resistencia",
      "Samuhú",
      "San Bernardo",
      "Santa Sylvina",
      "Taco Pozo",
      "Tres Isletas",
      "Villa Berthet",
      "Villa Río Bermejito",
      "Villa Ángela",
    ],
  },
  {
    name: "Chubut",
    zones: [
      "Aldea Beleiro",
      "Aldea Epulef",
      "Alto Río Senguer",
      "Buen Pasto",
      "Camarones",
      "Carrenleufú",
      "Cholila",
      "Colan Conhué",
      "Comodoro Rivadavia",
      "Corcovado",
      "Cushamen",
      "Dique Florentino Ameghino",
      "Doctor Ricardo Rojas",
      "Dolavon",
      "El Hoyo",
      "El Maitén",
      "Epuyén",
      "Esquel",
      "Facundo",
      "Gaiman",
      "Gan Gan",
      "Gastre",
      "Gobernador Costa",
      "Gualjaina",
      "José de San Martín",
      "Lago Blanco",
      "Lago Puelo",
      "Lagunita Salada",
      "Las Plumas",
      "Los Altares",
      "Paso de los Indios",
      "Paso del Sapo",
      "Puerto Madryn",
      "Puerto Pirámide",
      "Rawson",
      "Río Mayo",
      "Río Pico",
      "Sarmiento",
      "Tecka",
      "Telsen",
      "Trelew",
      "Trevelín",
      "Veintiocho de Julio",
      "Cerro Centinela",
      "Aldea Apeleg",
      "Atilio Viglione",
    ],
  },
  {
    name: "Córdoba",
    zones: [
      "Achiras",
      "Adelia María",
      "Agua de Oro",
      "Alcira Gigena",
      "Alejandro Roca",
      "Alejo Ledesma",
      "Alicia",
      "Almafuerte",
      "Alpa Corral",
      "Alta Garcia",
      "Alto Alegre",
      "Altos de Chipión",
      "Anisacate",
      "Arias",
      "Arroyito",
      "Arroyo Algodón",
      "Arroyo Cabral",
      "Ausonia",
      "Ballesteros",
      "Ballesteros Sud",
      "Balnearia",
      "Bell Ville",
      "Bengolea",
      "Benjamín Gould",
      "Berrotarán",
      "Bialet Massé",
      "Bouwer",
      "Brinkmann",
      "Buchardo",
      "Bulnes",
      "Calchín",
      "Calchín Oeste",
      "Camilo Aldao",
      "Canals",
      "Capilla del Carmen",
      "Capilla del Monte",
      "Capitán General Bernardo O'Higgins",
      "Carnerillo",
      "Carrilobo",
      "Cavanagh",
      "Cañada de Luque",
      "Chaján",
      "Charras",
      "Chazón",
      "Chilibroste",
      "Cintra",
      "Colazo",
      "Colonia Almada",
      "Colonia Bismarck",
      "Colonia Caroya",
      "Colonia Italiana",
      "Colonia Marina",
      "Colonia Prosperidad",
      "Colonia San Bartolomé",
      "Colonia Tirolesa",
      "Colonia Vignaud",
      "Coronel Baigorria",
      "Coronel Moldes",
      "Corral de Bustos",
      "Corralito",
      "Cosquín",
      "Costa Sacate",
      "Cruz Alta",
      "Cruz del Eje",
      "Córdoba",
      "Dalmacio Vélez Sarfield",
      "Del Campillo",
      "Despeñaderos",
      "Devoto",
      "Deán Funes",
      "El Arañado",
      "El Brete",
      "El Fortín",
      "El Tío",
      "Elena",
      "Emblase",
      "Estación General Paz",
      "Estación Juárez Celman",
      "Etruria",
      "Freyre",
      "General Baldissera",
      "General Cabrera",
      "General Deheza",
      "General Levalle",
      "General Roca",
      "Guatimozín",
      "Hernando",
      "Huanchilla",
      "Huerta Grande",
      "Huinca Renancó",
      "Idiazábal",
      "Inriville",
      "Isla Verde",
      "Italó",
      "James Craik",
      "Jesús María",
      "Jovita",
      "Justiniano Posse",
      "La Calera",
      "La Carlota",
      "La Cautiva",
      "La Cesira",
      "La Cruz",
      "La Cumbre",
      "La Falda",
      "La Francia",
      "La Granja",
      "La Laguna",
      "La Palestina",
      "La Paquita",
      "La Para",
      "La Paz",
      "La Playosa",
      "La Puerta",
      "La Tordilla",
      "Laborde",
      "Laboulaye",
      "Laguna Larga",
      "Las Acequias",
      "Las Arrias",
      "Las Higueras",
      "Las Junturas",
      "Las Perdices",
      "Las Peñas",
      "Las Tapias",
      "Las Varas",
      "Las Varillas",
      "Las Vertientes",
      "Leones",
      "Los Cerrillos",
      "Los Cisnes",
      "Los Cocos",
      "Los Cóndores",
      "Los Surgentes",
      "Los Zorros",
      "Lozada",
      "Luca",
      "Lucio V. Mansilla",
      "Luque",
      "Malagueño",
      "Malvinas Argentinas",
      "Manfredi",
      "Marcos Juárez",
      "Marull",
      "Matorrales",
      "Mattaldi",
      "Melo",
      "Mendiolaza",
      "Mi Granja",
      "Mina Clavero",
      "Miramar de Ansenuza",
      "Monte Buey",
      "Monte Cristo",
      "Monte de los Gauchos",
      "Monte Leña",
      "Monte Maíz",
      "Monte Ralo",
      "Morrison",
      "Morteros",
      "Noeinger",
      "Nono",
      "Obispo Trejo",
      "Olaeta",
      "Oliva",
      "Oncativo",
      "Ordóñez",
      "Pampayasta Sud",
      "Pascanas",
      "Pasco",
      "Pilar",
      "Piquillín",
      "Porteña",
      "Pozo del Molle",
      "Pueblo Italiano",
      "Quebrancho Herrado",
      "Quilino",
      "Reducción",
      "Rosales",
      "Río Ceballos",
      "Río Cuarto",
      "Río de los Sauces",
      "Río Primero",
      "Río Segundo",
      "Río Tercero",
      "Sacanta",
      "Saira",
      "Saldán",
      "Salsacate",
      "Salsipuedes",
      "Sampacho",
      "San Agustín",
      "San Antonio de Arredondo",
      "San Antonio de Litín",
      "San Basilio",
      "San Carlos Minas",
      "San Esteban",
      "San Francisco",
      "San Francisco del Chañar",
      "San Javier y Yacanto",
      "San José",
      "San José de la Dormida",
      "San José de las Salinas",
      "San Marco Sierras",
      "San Marcos Sud",
      "San Pedro",
      "San Pedro Norte",
      "Santa Catalina",
      "Santa Eufemia",
      "Santa María de Punilla",
      "Santa Rosa de Calamuchita",
      "Santa Rosa de Río Primero",
      "Santiago Temple",
      "Sarmiento",
      "Saturnino María Laspiur",
      "Sebastián Elcano",
      "Seeber",
      "Serrano",
      "Serrezuela",
      "Silvio Pellico",
      "Sinsacate",
      "Tancacha",
      "Tanti",
      "Ticino",
      "Toledo",
      "Tosquita",
      "Tránsito",
      "Tío Pujio",
      "Ucacha",
      "Unquillo",
      "Valle Hermoso",
      "Viamonte",
      "Vicuña Mackenna",
      "Villa Allende",
      "Villa Ascasubi",
      "Villa Carlos Paz",
      "Villa Concepción del Tío",
      "Villa Cura Brochero",
      "Villa de las Rosas",
      "Villa de María del Río Seco",
      "Villa de Soto",
      "Villa del Dique",
      "Villa del Rosario",
      "Villa del Totoral",
      "Villa Dolores",
      "Villa Fontana",
      "Villa General Belgrano",
      "Villa Giardino",
      "Villa Huidobro",
      "Villa Icho Cruz",
      "Villa María",
      "Villa Nueva",
      "Villa Parque Santa Ana",
      "Villa Rossi",
      "Villa Rumipal",
      "Villa Santa Cruz del Lago",
      "Villa Sarmiento",
      "Villa Tulumba",
      "Villa Valeria",
      "Villa Yacanto",
      "Wenceslao Escalante",
    ],
  },
  {
    name: "Corrientes",
    zones: [
      "Bella Vista",
      "Berón de Astrada",
      "Bonpland",
      "Cazadores Correntinos",
      "Caá Catí",
      "Cecilio Echevarría",
      "Chavarría",
      "Colonia Carlos Pellegrini",
      "Colonia Carolina",
      "Colonia Libertad",
      "Colonia Liebig",
      "Colonia Pando",
      "Concepción del Yaguareté Corá",
      "Corrientes",
      "Cruz de los Milagros",
      "Curuzú Cuatiá",
      "El Sombrero",
      "Empedrado",
      "Esquina",
      "Estación Torrent",
      "Felipe Yofre",
      "Garruchos",
      "General Alvear",
      "Gobernador Ing. Valentín Virasoro",
      "Gobernador Martínez",
      "Goya",
      "Guaviraví",
      "Herlitzka",
      "Itatí",
      "Ituzaingó",
      "Itá Ibaté",
      "José Rafael Gómez",
      "Juan Pujol",
      "La Cruz",
      "Lavalle",
      "Lomas de Vallejos",
      "Loreto",
      "Mariano I. Loza",
      "Mburucuyá",
      "Mercedes",
      "Mocoretá",
      "Monte Caseros",
      "Nueve de Julio",
      "Pago de los Deseos",
      "Palmar Grande",
      "Parada Pucheta",
      "Paso de la Patria",
      "Paso de los Libres",
      "Pedro R. Fernández",
      "Perugorría",
      "Pueblo Libertador",
      "Ramada Paso",
      "Riachuelo",
      "Saladas",
      "San Antonio de Apipé",
      "San Carlos",
      "San Cosme",
      "San Isidro",
      "San Lorenzo",
      "San Luis del Palmar",
      "San Miguel",
      "San Roque",
      "Santa Ana de los Guácaras",
      "Santa Lucía",
      "Santa Rosa",
      "Santo Tomé",
      "Sauce",
      "Tabay",
      "Tapebicuá",
      "Tatacuá",
      "Tres de Abril",
      "Villa Olivari",
      "Yapeyú",
      "Yataytí Calle",
    ],
  },
  {
    name: "Entre Ríos",
    zones: [
      "Aldea Brasilera",
      "Aldea María Luisa",
      "Aldea San Antonio",
      "Aranguren",
      "Basavilbaso",
      "Bovril",
      "Caseros",
      "Ceibas",
      "Cerrito",
      "Chajarí",
      "Colonia Avellaneda",
      "Colonia Ayuí",
      "Colonia Elía",
      "Colón",
      "Concepción del Uruguay",
      "Concordia",
      "Conscripto Bernardi",
      "Crespo",
      "Diamante",
      "El Pingo",
      "Enrique Carbó",
      "Estancia Grande",
      "Federación",
      "Federal",
      "General Campos",
      "General Galarza",
      "General Ramírez",
      "Gilbert",
      "Gobernador Maciá",
      "Goberador Mansilla",
      "Gualeguay",
      "Gualeguaychú",
      "Hasenkamp",
      "Hernández",
      "Herrera",
      "Ibicuy",
      "La Criolla",
      "La Paz",
      "Larroque",
      "Libertador San Martín",
      "Los Charrúas",
      "Los Conquistadores",
      "Lucas González",
      "María Grande",
      "Nogoyá",
      "Oro Verde",
      "Paraná",
      "Piedras Blancas",
      "Primero de Mayo",
      "Pronunciamiento",
      "Pueblo Brugo",
      "Pueblo General Belgrano",
      "Pueblo Liebig",
      "Puerto Yeruá",
      "Rosario del Tala",
      "San Benito",
      "San Gustavo",
      "San Jaime de la Frontera",
      "San José",
      "San José de Feliciano",
      "San Justo",
      "San Salvador",
      "Santa Ana",
      "Santa Anita",
      "Santa Elena",
      "Sauce de Luna",
      "Seguí",
      "Tabossi",
      "Ubajay",
      "Urdinarrain",
      "Valle María",
      "Viale",
      "Victoria",
      "Villa Alcaraz",
      "Villa Clara",
      "Villa del Rosario",
      "Villa Domínguez",
      "Villa Elisa",
      "Villa Hernandarias",
      "Villa Mantero",
      "Villa Paranacito",
      "Villa Urquiza",
      "Villaguay",
    ],
  },
  {
    name: "Formosa",
    zones: [
      "Clorinda",
      "Comandante Fontana",
      "El Colorado",
      "El Espinillo",
      "Estanislao del Campo",
      "Formosa",
      "General Enrique Mosconi",
      "General Lucio Victorio Mansilla",
      "General Manuel Belgrano",
      "Herradura",
      "Ibarreta",
      "Ingeniero Guillermo Nicasio Juárez",
      "Laguna Blanca",
      "Laguna Naick Neck",
      "Laguna Yema",
      "Las Lomitas",
      "Mayor Vicente Villafañe",
      "Misión San Francisco de Laishí",
      "Misión Tacaaglé",
      "Palo Santo",
      "Pirané",
      "Pozo del Tigre",
      "Riacho He-Hé",
      "San Martín Dos",
      "Villa Dos Trece",
      "Villa Escolar",
      "Villa General Güemes",
    ],
  },
  {
    name: "Jujuy",
    zones: [
      "Abra Pampa",
      "Aguas Calientes",
      "Caimancito",
      "Calilegua",
      "El Aguilar",
      "El Carmen",
      "El Talar",
      "Fraile Pintado",
      "Humahuaca",
      "La Esperanza",
      "La Mendieta",
      "La Quiaca",
      "Libertador General San Martín",
      "Maimará",
      "Monterrico",
      "Palma Sola",
      "Palpalá",
      "Pampa Blanca",
      "Perico",
      "Puesto Viejo",
      "San Antonio",
      "San Pedro de Jujuy",
      "San Salvador de Jujuy",
      "Santa Clara",
      "Tilcara",
      "Yala",
      "Yuto",
    ],
  },
  {
    name: "La Pampa",
    zones: [
      "Abramo",
      "Algarrobo del Águila",
      "Alpachiri",
      "Alta Italia",
      "Anguil",
      "Arata",
      "Ataliva Roca",
      "Bernardo Larroudé",
      "Bernasconi",
      "Caleufú",
      "Carro Quemado",
      "Catriló",
      "Ceballos",
      "Colonia 25 de Mayo",
      "Colonia Barón",
      "Colonia Santa Teresa",
      "Conhello",
      "Coronel Hilario Lagos",
      "Doblas",
      "Dorila",
      "Eduardo Castex",
      "Embajador Martini",
      "General Acha",
      "General Manuel Campos",
      "General Pico",
      "General San Martín",
      "Gobernador Duval",
      "Guatraché",
      "Ingeniero Luiggi",
      "Intendente Alvear",
      "Jacinto Arauz",
      "La Adela",
      "La Humada",
      "La Maruja",
      "Lonquimay",
      "Luan Toro",
      "Macachín",
      "Mauricio Mayer",
      "Metileo",
      "Miguel Cané",
      "Miguel Riglos",
      "Monte Nievas",
      "Parera",
      "Puelches",
      "Puelén",
      "Quehué",
      "Quemú Quemú",
      "Rancul",
      "Realicó",
      "Rolón",
      "Santa Isabel",
      "Santa Rosa",
      "Telén",
      "Toay",
      "Tomás Manuel Anchorena",
      "Trenel",
      "Uriburu",
      "Victorica",
      "Villa Mirasol",
      "Vértiz",
      "Winifreda",
    ],
  },
  {
    name: "La Rioja",
    zones: [
      "Aimogasta",
      "Aminga",
      "Chamical",
      "Chepes",
      "Chilecito",
      "Famatina",
      "La Rioja",
      "Los Sauces",
      "Malanzán",
      "Olta",
      "Patquía",
      "Tama",
      "Ulapes",
      "Villa Castelli",
      "Villa San José de Vinchina",
      "Villa Sanagasta",
      "Villa Santa Rita de Catuna",
      "Villa Unión",
    ],
  },
  {
    name: "Mendoza",
    zones: [
      "General Alvear",
      "Godoy Cruz",
      "Junín",
      "La Paz",
      "Las Heras",
      "Luján de Cuyo",
      "Maipú",
      "Malargüe",
      "Mendoza",
      "Rivadavia",
      "San Martín",
      "San Rafael",
      "Santa Rosa",
      "Guaymallén",
      "Tunuyán",
      "Tupungato",
      "San Carlos",
      "Lavalle",
    ],
  },
  {
    name: "Misiones",
    zones: [
      "Alba Posse",
      "Almafuerte",
      "Apóstoles",
      "Aristóbulo del Valle",
      "Arrollo del Medio",
      "Azara",
      "Bernardo de Irigoyen",
      "Bonpland",
      "Campo Grande",
      "Campo Ramón",
      "Campo Viera",
      "Candelaria",
      "Capioví",
      "Caraguatay",
      "Caá Yari",
      "Cerro Azul",
      "Cerro Corá",
      "Colonia Alberdi",
      "Colonia Aurora",
      "Colonia Delicia",
      "Colonia Polana",
      "Colonia Victoria",
      "Colonia Wanda",
      "Comandante Andrés Guacurari",
      "Concepción de la Sierra",
      "Corpus",
      "Dos Arroyos",
      "Dos de Mayo",
      "El Alcázar",
      "El Soberbio",
      "El Dorado",
      "Fachinal",
      "Florentino Ameghino",
      "Fracán",
      "Garuhapé",
      "Garupá",
      "General Alvear",
      "General Urqiza",
      "Gobernador Lopez",
      "Gobernador Roca",
      "Guaraní",
      "Hipólito Yrigoyen",
      "Itacaruaré",
      "Jardín América",
      "Leandro N. Alem",
      "Loreto",
      "Los Helechos",
      "Mojón Grande",
      "Montecarlo",
      "Mártires",
      "Nueve de Julio",
      "Oberá",
      "Olegario Víctor Andrade",
      "Panambí",
      "Posadas",
      "Pozo Azul",
      "Profundidad",
      "Puerto Esperanza",
      "Puerto Iguazú",
      "Puerto Leoni",
      "Puerto Libertad",
      "Puerto Piray",
      "Puerto Rico",
      "Ruiz de Montoya",
      "Salto Encantado",
      "San Antonio",
      "San Ignacio",
      "San Javier",
      "San José",
      "San Martín",
      "San Pedro",
      "San Vicente",
      "Santa Ana",
      "Santa María",
      "Santiago de Liniers",
      "Santo Pipó",
      "Tres Capones",
      "Veinticinco de Mayo",
    ],
  },
  {
    name: "Neuquén",
    zones: [
      "Aluminé",
      "Andacollo",
      "Añelo",
      "Bajada del Agrio",
      "Barrancadas",
      "Buta Ranquil",
      "Caviahue-Copahue",
      "Centenario",
      "Chos Malal",
      "Cutral-Có",
      "El Cholar",
      "El Huecú",
      "HuiganCó",
      "Junín de los Andes",
      "Las Coloradas",
      "Las Lajas",
      "Las Ovejas",
      "Loncopué",
      "Los Miches",
      "Mariano Moreno",
      "Neuquén",
      "Picún Leufú",
      "Piedra del Águila",
      "Plaza Huincul",
      "Plottier",
      "Rincón de los Sauces",
      "San Martín de los Andes",
      "San Patricio del Chañar",
      "Senillosa",
      "Taquimilán",
      "Tricao Malal",
      "Villa el Chocón",
      "Villa la Angostura",
      "Villa Pehuenia",
      "Vista Alegre",
      "Zapala",
    ],
  },
  {
    name: "Río Negro",
    zones: [
      "Allen",
      "Campo Grande",
      "Catriel",
      "Cervantes",
      "Chinchinales",
      "Chimpay",
      "Choele Choel",
      "Cinco Saltos",
      "Cipolletti",
      "Comallo",
      "Contralmirante Cordero",
      "Coronel Belisle",
      "Darwin",
      "Dina Huapi",
      "El Bolsón",
      "General Conesa",
      "General Enrique Godoy",
      "General Fernández Oro",
      "General Roca",
      "Guardia Mitre",
      "Ingeniero Jacobacci",
      "Ingeniero Luis A. Huergo",
      "Lamarque",
      "Los Menucos",
      "Luis Beltrán",
      "Mainqué",
      "Maquinchao",
      "Ministro Ramos Mexía",
      "Pilcaniyeu",
      "Pomona",
      "Río Colorado",
      "San Antonio Oeste",
      "San Carlos de Bariloche",
      "Sierra Colorada",
      "Sierra Grande",
      "Valcheta",
      "Viedma",
      "Villa Regina",
      "Ñorquincó",
    ],
  },
  {
    name: "Salta",
    zones: [
      "Aguaray",
      "Aguas Blancas",
      "Angastaco",
      "Animaná",
      "Apolinario Saravia",
      "Cachi",
      "Cafayate",
      "Campo Quijano",
      "Campo Santo",
      "Cerrillos",
      "Chicoana",
      "Colonia Santa Rosa",
      "Coronel Moldes",
      "El Bordo",
      "El Carril",
      "El Galpón",
      "El Jardín",
      "El Potrero",
      "El Quebranchal",
      "El Tala",
      "Embarcación",
      "General Ballivián",
      "General Güemes",
      "General Mosconi",
      "General Pizarro",
      "Guachipas",
      "Hipólito Yrigoyen",
      "Iruya",
      "Isla de Cañas",
      "Joaquín Víctor González",
      "La Caldera",
      "La Candelaria",
      "La Merced",
      "La Poma",
      "La Viña",
      "Las Lajitas",
      "Los Toldos",
      "Molinos",
      "Nazareno",
      "Payogasta",
      "Pichanal",
      "Profesor Salvador Mazza",
      "Rivadavia Banda Norte",
      "Rivadavia Banda Sur",
      "Rosario de la Frontera",
      "Rosario de Lerma",
      "Río Piedras",
      "Salta",
      "San Antonio de Los Cobres",
      "San Carlos",
      "San José de Metán",
      "San Ramón de la Nueva Orán",
      "Santa Victoria Este",
      "Santa Victoria Oeste",
      "Seclantás",
      "Tartagal",
      "Tolar Grande",
      "Urundel",
      "Vaqueros",
      "Villa San Lorenzo",
    ],
  },
  {
    name: "San Juan",
    zones: [
      "Albardón",
      "Angaco",
      "Calingasta",
      "Capital",
      "Caucete",
      "Chimbas",
      "Iglesia",
      "Jáchal",
      "Nueve de Julio",
      "Pocito",
      "Rawson",
      "Rivadavia",
      "San Martín",
      "Santa Lucía",
      "Sarmiento",
      "Ullum",
      "Valle Fértil",
      "Veinticinco de Mayo",
      "Zonda",
    ],
  },
  {
    name: "San Luis",
    zones: [
      "Anchorena",
      "Arizona",
      "Buena Esperanza",
      "Candelaria",
      "Concarán",
      "El Volcán",
      "Juana Koslay",
      "Justo Daract",
      "La Punta",
      "La Toma",
      "Luján",
      "Naschel",
      "Nogolí",
      "Quines",
      "San Francisco del Monte de Oro",
      "San Luis",
      "San Martín",
      "Santa Rosa del Conlara",
      "Tilisarao",
      "Unión",
      "Villa de Merlo",
      "Villa General Roca",
      "Villa Mercedes",
    ],
  },
  {
    name: "Santa Cruz",
    zones: [
      "Caleta Olivia",
      "Comandante Luis Piedrabuena",
      "El Calafate",
      "El Chaltén",
      "Gobernador Gregores",
      "Las Heras",
      "Los Antiguos",
      "Perito Moreno",
      "Pico Truncado",
      "Puerto Deseado",
      "Puerto San Julián",
      "Puerto Santa Cruz",
      "Río Gallegos",
      "Río Turbio",
      "Veintiocho de Noviembre",
    ],
  },
  {
    name: "Santa Fe",
    zones: [
      "Armstrong",
      "Arroyo Seco",
      "Avellaneda",
      "Calchaquí",
      "Capitán Bermúdez",
      "Carcarañá",
      "Casilda",
      "Cañada de Gómez",
      "Ceres",
      "Coronda",
      "El Trébol",
      "Esperanza",
      "Firmat",
      "Florencia",
      "Fray Luis Beltrán",
      "Frontera",
      "Funes",
      "Granadero Baigorria",
      "Gálvez",
      "Laguna Paiva",
      "Las Parejas",
      "Las Rosas",
      "Las Toscas",
      "Malabrigo",
      "Pueblo Esther",
      "Puerto General San Martín",
      "Pérez",
      "Rafaela",
      "Reconquista",
      "Recreo",
      "Roldán",
      "Romang",
      "Rosario",
      "Rufino",
      "San Carlos Centro",
      "San Cristóbal",
      "San Genaro",
      "San Guillermo",
      "San Javier",
      "San Jerónimo Norte",
      "San Jorge",
      "San José del Rincón",
      "San Justo",
      "San Lorenzo",
      "Santa Fe",
      "Santo Tomé",
      "Sastre",
      "Suardi",
      "Sunchales",
      "Tostado",
      "Totoras",
      "Venado Tuerto",
      "Vera",
      "Villa Cañás",
      "Villa Constitución",
      "Villa Gobernador Gálvez",
      "Villa Ocampo",
    ],
  },
  {
    name: "Santiago del Estero",
    zones: [
      "Añatuya",
      "Bandera",
      "Beltrán",
      "Campo Gallo",
      "Clodomira",
      "Colonia Dora",
      "Fernández",
      "Frías",
      "Ingeniero Forres",
      "La Banda",
      "Loreto",
      "Los Juríes",
      "Los Telares",
      "Monte Quemado",
      "Nueva Esperanza",
      "Pampa de los Guanacos",
      "Pinto",
      "Pozo Hondo",
      "Quimilí",
      "San Pedro de Guasayán",
      "Santiago del Estero",
      "Selva",
      "Sumampa",
      "Suncho Corral",
      "Termas de Río Hondo",
      "Tintina",
      "Villa Atamisqui",
      "Villa Ojo de Agua",
    ],
  },
  {
    name: "Tierra del Fuego",
    zones: ["Ushuaia", "Río Grande", "Tolhuin"],
  },
  {
    name: "Tucumán",
    zones: [
      "Aguilares",
      "Aldaretes",
      "Banda del Río Salí",
      "Bella Vista",
      "Burruyacú",
      "Concepción",
      "Famaillá",
      "Graneros",
      "Juan Bautista Alberdi",
      "La Cocha",
      "Las Talitas",
      "Lules",
      "Monteros",
      "San Miguel de Tucumán",
      "Simoca",
      "Tafí del Valle",
      "Tafí Viejo",
      "Trancas",
      "Yerba Buena",
    ],
  },
  {
    name: "Ciudad Autónoma de Buenos Aires",
    zones: [
      "Retiro",
      "San Nicolás",
      "Puerto Madero",
      "San Telmo",
      "Montserrat",
      "Constitución",
      "Recoleta",
      "Balvanera",
      "San Cristóbal",
      "La Boca",
      "Barracas",
      "Parque Patricios",
      "Nueva Pompeya",
      "Almagro",
      "Boedo",
      "Caballito",
      "Flores",
      "Parque Chacabuco",
      "Villa Soldati",
      "Villa Riachuelo",
      "Villa Lugano",
      "Liniers",
      "Mataderos",
      "Parque Avellaneda",
      "Villa Real",
      "Monte Castro",
      "Versalles",
      "Floresta",
      "Vélez Sarsfield",
      "Villa Luro",
      "Villa General Mitre",
      "Villa Devoto",
      "Villa del Parque",
      "Villa Santa Rita",
      "Coghlan",
      "Saavedra",
      "Villa Urquiza",
      "Villa Pueyrredón",
      "Núñez",
      "Belgrano",
      "Colegiales",
      "Palermo",
      "Chacarita",
      "Villa Crespo",
      "La Paternal",
      "Villa Ortúzar",
      "Agronomía",
      "Parque Chas",
    ],
  },
];
