export const countryName: string = "Argentina";

export const statesData = [
  {
    name: "Buenos Aires",
    zones: [
      "Adolfo Alsina",
      "Adolfo González Chaves",
      "Alberti",
      "Almirante Brown",
      "Arrecifes",
      "Avellaneda",
      "Ayacucho",
      "Azul",
      "Bahía Blanca",
      "Balcarce",
      "Baradero",
      "Benito Juárez",
      "Berazategui",
      "Berisso",
      "Bolívar",
      "Bragado",
      "Brandsen",
      "Campana",
      "Capitán Sarmiento",
      "Carlos Casares",
      "Carlos Tejedor",
      "Carmen de Areco",
      "Castelli",
      "Colón",
      "Coronel Dorrego",
      "Coronel Pringles",
      "Coronel Rosales",
      "Coronel Suárez",
      "Chacabuco",
      "Chascomús",
      "Chivilcoy",
      "Daireaux",
      "Dolores",
      "Ensenada",
      "Escobar",
      "Esteban Echeverría",
      "Exaltación de la Cruz",
      "Ezeiza",
      "Florencio Varela",
      "Florentino Ameghino",
      "General Alvarado",
      "General Alvear",
      "General Arenales",
      "General Belgrano",
      "General Guido",
      "General La Madrid",
      "General Las Heras",
      "General Lavalle",
      "General Madariaga",
      "General Paz",
      "General Pinto",
      "General Pueyrredón",
      "General Rodríguez",
      "General San Martín",
      "General Viamonte",
      "General Villegas",
      "Guaminí",
      "Hipólito Yrigoyen",
      "Hurlingham",
      "Ituzaingó",
      "José C. Paz",
      "Junín",
      "La Costa",
      "La Matanza",
      "La Plata",
      "Lanús",
      "Laprida",
      "Las Flores",
      "Leandro N. Alem",
      "Lezama",
      "Lincoln",
      "Lobería",
      "Lobos",
      "Lomas de Zamora",
      "Lujan",
      "Magdalena",
      "Maipú",
      "Malvinas Argentinas",
      "Mar Chiquita",
      "Marcos Paz",
      "Mercedes",
      "Merlo",
      "Monte Hermoso",
      "Moreno",
      "Morón",
      "Navarro",
      "Necochea",
      "Nueve de Julio",
      "Olavarría",
      "Patagones",
      "Pehuajó",
      "Pellegrini",
      "Pergamino",
      "Pila",
      "Pilar",
      "Pinamar",
      "Presidente Perón",
      "Punta Indio",
      "Quilmes",
      "Ramallo",
      "Rauch",
      "Rivadavia",
      "Rojas",
      "Roque Pérez",
      "Saavedra",
      "Saladillo",
      "Salliquelo",
      "Salto",
      "San Andrés de Giles",
      "San Antonio de Areco",
      "San Cayetano",
      "San Fernando",
      "San Isidro",
      "San Miguel",
      "San Miguel del Monte",
      "San Nicolás",
      "San Pedro",
      "San Vicente",
      "Suipacha",
      "Tandil",
      "Tapalqué",
      "Tigre",
      "Tordillo",
      "Tornquist",
      "Trenque Lauquen",
      "Tres Arroyos",
      "Tres de Febrero",
      "Tres Lomas",
      "Veinticinco de Mayo",
      "Vicente López",
      "Villa Gesell",
      "Villarino",
      "Zárate",
    ],
  },
  {
    name: "Catamarca",
    zones: [
      "Aconquija",
      "Ancasti",
      "Andalgalá",
      "Antofagasta de la Sierra",
      "Belén",
      "Capayán",
      "Corral Quemado",
      "El Alto",
      "El Rodeo",
      "Fiambalá",
      "Fray Mamerto Esquiú",
      "Hualfín",
      "Huillapima",
      "Icaño",
      "La Puerta",
      "Las Juntas",
      "Londres",
      "Los Altos",
      "Los Varela",
      "Mutquín",
      "Paclín",
      "Poman",
      "Pozo de Piedra",
      "Puerta de Corral Quemado",
      "Puerta de San José",
      "Recreo",
      "San Fernando",
      "San Fernando del Valle de Catamarca",
      "San José",
      "Santa María",
      "Santa Rosa",
      "Saujil",
      "Tapso",
      "Tinogasta",
      "Valle Viejo",
      "Villa Vil",
    ],
  },
  {
    name: "Chaco",
    zones: [
      "Aviá Teraí",
      "Barranqueras",
      "Basail",
      "Campo Largo",
      "Capitán Solari",
      "Charadai",
      "Charata",
      "Chorotis",
      "Ciervo Petiso",
      "Colonia Aborigen",
      "Colonia Benítez",
      "Colonia Elisa",
      "Colonia Popular",
      "Colonias Unidas",
      "Concepción del Bermejo",
      "Coronel Du Graty",
      "Corzuela",
      "Cote Lai",
      "El Espinillo",
      "El Sauzalito",
      "Enrique Urién",
      "Fontana",
      "Fuerte Esperanza",
      "Gancedo",
      "General Capdevila",
      "General José de San Martín",
      "General Pinedo",
      "General Vedia",
      "Hermoso Campo",
      "Isla del Cerrito",
      "Juan José Castelli",
      "La Clotilde",
      "La Eduvigis",
      "La Escondida",
      "La Leonesa",
      "La Tigra",
      "La Verde",
      "Laguna Blanca",
      "Laguna Limpia",
      "Lapachito",
      "Las Breñas",
      "Las Garcitas",
      "Las Palmas",
      "Los Frentones",
      "Machagai",
      "Makallé",
      "Margarita Belén",
      "Miraflores",
      "Misión Nueva Pompeya",
      "Napenay",
      "Pampa Almirón",
      "Pampa del Indio",
      "Pampa del Infierno",
      "Presidencia de la Plaza",
      "Presidencia Roca",
      "Presidencia Roque Sáenz Peña",
      "Puerto Bermejo",
      "Puerto Eva Perón",
      "Puerto Tirol",
      "Puerto Vilelas",
      "Quitilipi",
      "Resistencia",
      "Samuhú",
      "San Bernardo",
      "Santa Sylvina",
      "Taco Pozo",
      "Tres Isletas",
      "Villa Berthet",
      "Villa Río Bermejito",
      "Villa Ángela",
    ],
  },
  {
    name: "Chubut",
    zones: [
      "Aldea Beleiro",
      "Aldea Epulef",
      "Alto Río Senguer",
      "Buen Pasto",
      "Camarones",
      "Carrenleufú",
      "Cholila",
      "Colan Conhué",
      "Comodoro Rivadavia",
      "Corcovado",
      "Cushamen",
      "Dique Florentino Ameghino",
      "Doctor Ricardo Rojas",
      "Dolavon",
      "El Hoyo",
      "El Maitén",
      "Epuyén",
      "Esquel",
      "Facundo",
      "Gaiman",
      "Gan Gan",
      "Gastre",
      "Gobernador Costa",
      "Gualjaina",
      "José de San Martín",
      "Lago Blanco",
      "Lago Puelo",
      "Lagunita Salada",
      "Las Plumas",
      "Los Altares",
      "Paso de los Indios",
      "Paso del Sapo",
      "Puerto Madryn",
      "Puerto Pirámide",
      "Rawson",
      "Río Mayo",
      "Río Pico",
      "Sarmiento",
      "Tecka",
      "Telsen",
      "Trelew",
      "Trevelín",
      "Veintiocho de Julio",
      "Cerro Centinela",
      "Aldea Apeleg",
      "Atilio Viglione",
    ],
  },
  {
    name: "Córdoba",
    zones: ["Córdoba", "Villa Carlos Paz", "Río Cuarto", "Villa María"],
  },
  {
    name: "Corrientes",
    zones: ["Corrientes", "Goya", "Mercedes"],
  },
  {
    name: "Entre Ríos",
    zones: ["Paraná", "Concordia", "Gualeguaychú"],
  },
  {
    name: "Formosa",
    zones: ["Formosa", "Clorinda", "Pirané"],
  },
  {
    name: "Jujuy",
    zones: [
      "San Salvador de Jujuy",
      "Palpalá",
      "Libertador General San Martín",
    ],
  },
  {
    name: "La Pampa",
    zones: ["Santa Rosa", "General Pico", "Toay"],
  },
  {
    name: "La Rioja",
    zones: ["La Rioja", "Chilecito", "Aimogasta"],
  },
  {
    name: "Mendoza",
    zones: [
      "General Alvear",
      "Godoy Cruz",
      "Junín",
      "La Paz",
      "Las Heras",
      "Luján de Cuyo",
      "Maipú",
      "Malargüe",
      "Mendoza",
      "Rivadavia",
      "San Martín",
      "San Rafael",
      "Santa Rosa",
      "Guaymallén",
      "Tunuyán",
      "Tupungato",
      "San Carlos",
      "Lavalle",
    ],
  },
  {
    name: "Misiones",
    zones: ["Posadas", "Oberá", "Eldorado"],
  },
  {
    name: "Neuquén",
    zones: ["Neuquén", "Cutral Có", "Zapala"],
  },
  {
    name: "Río Negro",
    zones: ["Viedma", "Bariloche", "General Roca"],
  },
  {
    name: "Salta",
    zones: ["Salta", "Tartagal", "Orán"],
  },
  {
    name: "San Juan",
    zones: ["San Juan", "Rawson", "Chimbas"],
  },
  {
    name: "San Luis",
    zones: ["San Luis", "Villa Mercedes", "Merlo"],
  },
  {
    name: "Santa Cruz",
    zones: ["Río Gallegos", "Caleta Olivia", "El Calafate"],
  },
  {
    name: "Santa Fe",
    zones: ["Santa Fe", "Rosario", "Rafaela"],
  },
  {
    name: "Santiago del Estero",
    zones: ["Santiago del Estero", "La Banda", "Termas de Río Hondo"],
  },
  {
    name: "Tierra del Fuego",
    zones: ["Ushuaia", "Río Grande", "Tolhuin"],
  },
  {
    name: "Tucumán",
    zones: ["San Miguel de Tucumán", "Tafí Viejo", "Concepción"],
  },
  {
    name: "Ciudad Autónoma de Buenos Aires",
    zones: ["Palermo", "Recoleta", "Flores", "Belgrano"],
  },
];
